apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: mongo-source-connector
  namespace: confluent
spec:
  # podTemplate:
  #   resources:
  #     limits:
  #       cpu: "500m"
  #       memory: "1Gi"
  #     requests:
  #       cpu: "100m"
  #       memory: "512Mi"
  name: connector
  class: "MongoDbAtlasSource"
  taskMax: 4
  configs:
    # name: "<my-connector-name>"
    kafka.auth.mode: "KAFKA_API_KEY"
    kafka.api.key: "REPLACEME"
    kafka.api.secret: "REPLACEME"
    topic.prefix: "k8smongo-"
    connection.host: "REPLACEME"
    connection.user: "REPLACEME"
    connection.password": "REPLACEME"
    database: "test"
    collection: "fromk8s"
    poll.await.time.ms: "5000"
    poll.max.batch.size: "1000"
    copy.existing: "true"
    output.data.format: "JSON"
    tasks.max: "1"
  connectRest:
    authentication:
      type: basic
      basic:
        secretRef: kafka-creds

---