apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - connect.yml
  - connector.yml

# secretGenerator:
# - name: kafka-creds
#   files:
#   - kafka-auth.txt
# - name: mongo-creds
#   files:
#   - mongo-user.txt
#   - mongo-password.txt
# - name: elastic-creds
#   files:
#   - elastic-user.txt
#   - elastic-password.txt
