# Key needs to be basix.txt
# Format is username: <password>
apiVersion: v1
kind: Secret
metadata:
  name: kafka-cluster-secret
type: Opaque
data:
  basic.txt: WDdNWTdBRkpFU09ZTlFERzogRzE5UHhLOGVCeDRablRoakZPa1RSNGIwcU4wNi9rdjFkWWdRNnpwMnRVL3d0WVlmelZKVVhiSVJpd2RIRkJMZQo=

---

# Key needs to be named plain.txt
# Format needs to be in username=<user>\npassword:<pass> like a txt file

# Files needs to be
# username=<user>
# password=<password>

# Couldn't get it to work via manifests so I ran
# kubectl create secret generic kafka-plain-auth-secret \
#   --from-file=plain.txt=./confluent/.secrets/kafka-plain-auth-secret.txt \
#   --namespace confluent


apiVersion: v1
kind: Secret
metadata:
  name: kafka-plain-auth-secret
type: Opaque
data:
  plain.txt: agagagagga

---
# Files needs to be
# username=<user>
# password=<password>
apiVersion: v1
kind: Secret
metadata:
  name: schema-registry-secrets
type: Opaque
data:
  basic.txt: dagaggaagag

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  credentials.txt: agagagag
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-secrets
type: Opaque
data:
  credentials.txt: dasdgagagag

---


