apiVersion: v1
kind: Secret
metadata:
  name: kafka-creds
type: Opaque
data:



---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
type: Opaque
data:


---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-creds
type: Opaque
data:

---