apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
namePrefix: dev-
commonLabels:
  environment: dev
resources:
- namespace.yml
bases:
  - ../../app_kustomize
patches:
  - configmap.yml
  - deployment.yml
  - service.yml
  - ingress.yml
# resources:
#   - namespace.yml
#   - configmap.yml
#   - deployment.yml
#   - service.yml