apiVersion: v1
kind: Deployment
metadata:
  name: dev-fastapitest-depoyment
  namespace: dev-fastapitest
spec:
  replicas: 2
  template:
    metadata:
      labels:
        editor: vscode
        test: yolo
    spec:
      containers:
      - name: myfastapitest
        image: myfastapitest:00:02
        #only set this to nbever if you want to use images you build locally
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
