kind: Service
apiVersion: v1
metadata:
  name: dev-fastapitest-service
  namespace: dev-fastapitest
spec:
  selector:
    app:  Selector Label
  type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  name-of-the-port
    port:  8000
    targetPort:  8000