######### TEST NAMESPACE #########
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ingress



######### DEPLOYMENT HELLO WORLD 1 #########
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: test-ingress
spec:
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-app-ext
  namespace: test-ingress
spec:
  type: ExternalName
  externalName: hello-world-app.test-ingress.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-app
  namespace: test-ingress
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  # type: NodePort
  type: LoadBalancer
  selector:
    app: hello-world-app



---
######### DEPLOYMENT HELLO WORLD 2 #########
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app2
  namespace: test-ingress
spec:
  selector:
    matchLabels:
      app: hello-world-app2
  template:
    metadata:
      labels:
        app: hello-world-app2
    spec:
      containers:
        - name: hello-world-app
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-app2-ext
  namespace: test-ingress
spec:
  type: ExternalName
  externalName: hello-world-app2.test-ingress.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-app2
  namespace: test-ingress
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  # type: NodePort
  type: LoadBalancer
  selector:
    app: hello-world-app2




---
######### TEST INGRESS #########
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: test-ingress
  annotations:
    nginx.org/proxy-connect-timeout: 3600s
    nginx.org/proxy-read-timeout: 3600s
    nginx.org/proxy-send-timeout: 3600s
spec:
  ingressClassName: nginx
  rules:
    - host: hello1.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-app
                port:
                  number: 80
    - host: hello2.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-app2
                port:
                  number: 80
