apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-fastapitest-deployment
  namespace: prod-fastapitest
  labels:
    app: myfastapiapp
spec:
  selector:
    matchLabels:
      app: myfastapiapp
  replicas: 1
  template:
    metadata:
      labels:
        environment: prod
        app: myfastapiapp
    spec:
      containers:
      - name: myfastapitest
        image: noctsol/fastapitest:00.02
        resources:
          limits:
            memory: "550Mi"
