apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

# In general, avoid using this, makes everything a pain in the ass
# namePrefix: dev-

commonLabels:
  environment: dev
resources:
- namespace.yml
- ../../base
patches:
  - path: configmap.yml
  - path: deployment.yml

  - patch: |-
      - op: replace
        path: ??????????
        value: fastapi
        target:
          kind: Ingress
          name: default-ingress
          labelSelector: example-label=rainbow,example-labelz=over

  # https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md
  # target:
  #   group: <optional group>
  #   version: <optional version>
  #   kind: <optional kind>
  #   name: <optional name or regex pattern>
  #   namespace: <optional namespace>
  #   labelSelector: <optional label selector>
  #   annotationSelector: <optional annotation selector>
